config:
  send_anonymous_usage_stats: False

default:
  outputs:

    dev: # User-Password config
      type: snowflake
      account: xbazwvg-uu54610
      user: DBT_CLOUD_DEV
      password: Dbtuser@2
      role: TRANSFORMER_DEV
      database: DEV
      warehouse: TRANSFORMING
      schema: dbt_smaddheshiya
      threads: 1
      client_session_keep_alive: False

  target: dev
